apiVersion: apps/v1alpha1
kind: Deployment
metadata:
  name: helloword
  labels:
    app: helloword
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloword    
      env: prod
  template:
    metadata:
      labels:
        app: helloword
        env: prod
    spec:
      containers:
      - name: helloword
        image: okteto/hello-world:python
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-helloword
  labels:                   #assign label to service
    app: helloword
    env: prod
spec:
  selector:
    app: helloword    #Selector values should match with Deployment's matchLabel
    env: prod
  type: LoadBalancer      #Supprted value ClusterIP, LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
